# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall

# Source file and target
SRCS = AcceptedB+tree2Level.cpp
TARGET = AcceptedB+tree2Level

# Rule to build and run
run: $(TARGET)

$(TARGET): $(SRCS)
    $(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET)
    .\$(TARGET)